/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (no auth required) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with password, receive Bearer token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/auto-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto-login for trusted embedding contexts (?embed=1)
         * @description Issues a token when all configured trigger conditions match:
         *     Referer in trusted_referers AND (optionally) client IP in trusted_ips.
         *     The client must assert that ?embed=1 was present in the URL.
         */
        post: operations["autoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if current Bearer token is valid */
        get: operations["verifyToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all active tokens */
        get: operations["listTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens/{token_prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a token by its prefix */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full system status snapshot */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/master": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle master switch on/off */
        patch: operations["setMaster"];
        trace?: never;
    };
    "/sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all sequences with current state */
        get: operations["listSequences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences/{sequence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single sequence */
        get: operations["getSequence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences/{sequence_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a sequence — resumes from snapshot if one exists, otherwise fresh start */
        post: operations["startSequence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences/{sequence_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a running sequence — writes resume_snapshot with remaining_min */
        post: operations["pauseSequence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sequences/{sequence_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort a running sequence — no snapshot, no resume */
        post: operations["stopSequence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/valves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live state of all configured valves */
        get: operations["listValves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all pending scheduled runs */
        get: operations["listPlans"];
        put?: never;
        /** Schedule a future run */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a scheduled plan */
        delete: operations["deletePlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated run history */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Effective settings (YAML defaults merged with DB overrides) */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update settings (partial — only provided fields are overwritten) */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user preferences (theme, language) — global, not per-token */
        get: operations["getPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user preferences */
        patch: operations["updatePreferences"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SequenceStatus: "idle" | "running" | "paused" | "disabled";
        /** @enum {string} */
        TriggerSource: "cron" | "manual" | "plan" | "resume";
        /** @enum {string} */
        AbortReason: "rain" | "watchdog" | "manual_stop" | "ha_disconnect";
        /** @enum {string} */
        ValveStateEnum: "on" | "off" | "unknown";
        ValveState: {
            id: string;
            zone_id: string;
            label: string;
            state: components["schemas"]["ValveStateEnum"];
            /** Format: date-time */
            on_since?: string | null;
            runtime_min?: number | null;
        };
        ZoneSummary: {
            id: string;
            label: string;
            valve_state: components["schemas"]["ValveStateEnum"];
        };
        CurrentRun: {
            zone_id: string;
            zone_label: string;
            /** Format: date-time */
            started_at: string;
            elapsed_min: number;
            remaining_min: number;
            total_min: number;
            triggered_by: components["schemas"]["TriggerSource"];
        };
        SequenceState: {
            id: string;
            label: string;
            status: components["schemas"]["SequenceStatus"];
            enabled: boolean;
            paused: boolean;
            factor_pct: number;
            factor_notes: components["schemas"]["FactorNotes"];
            schedule_label: string;
            /** Format: date-time */
            next_run_at?: string | null;
            zones: components["schemas"]["ZoneSummary"][];
            basis_min_per_zone: number;
            current_run?: (components["schemas"]["CurrentRun"] | null) | null;
        };
        StartSequenceRequest: {
            /** @description Override in minutes. null = use config default with factor applied. */
            duration_min?: number | null;
        };
        WeatherSummary: {
            temp_c: number;
            rain_24h_mm: number;
            wind_label: string;
            season_active: boolean;
        };
        FactorNotes: {
            season_off: boolean;
            wind_blocked: boolean;
            rain_factor_pct?: number | null;
            temp_delta_pct?: number | null;
        };
        FactorBreakdown: {
            temp_pct: number;
            rain_pct: number;
            combined_pct: number;
            wind_blocking_sequences: string[];
        };
        NextRunSummary: {
            sequence_id: string;
            sequence_label: string;
            /** Format: date-time */
            scheduled_at: string;
            duration_min: number;
        };
        SystemStatus: {
            master_on: boolean;
            ha_connected: boolean;
            weather: components["schemas"]["WeatherSummary"];
            today_factor: components["schemas"]["FactorBreakdown"];
            next_run?: (components["schemas"]["NextRunSummary"] | null) | null;
            after_next?: (components["schemas"]["NextRunSummary"] | null) | null;
            liters_today: number;
            liters_week: number;
        };
        Plan: {
            /** Format: uuid */
            id: string;
            sequence_id: string;
            sequence_label: string;
            /** Format: date-time */
            scheduled_at: string;
            duration_min?: number | null;
            estimated_liters?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        CreatePlanRequest: {
            sequence_id: string;
            /** @enum {string} */
            mode: "in_hours" | "at_datetime";
            /** @description Hours from now (in_hours) or ISO 8601 datetime string (at_datetime) */
            value: number | string;
            /** @description null = use config default */
            duration_min?: number | null;
        };
        HistoryEntry: {
            id: number;
            zone_id: string;
            zone_label: string;
            sequence_id: string;
            sequence_label: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at?: string | null;
            duration_min?: number | null;
            liters?: number | null;
            triggered_by: components["schemas"]["TriggerSource"];
            aborted: boolean;
            abort_reason?: (components["schemas"]["AbortReason"] | null) | null;
        };
        PaginatedHistory: {
            items: components["schemas"]["HistoryEntry"][];
            total: number;
            page: number;
            per_page: number;
        };
        TempFactorSettings: {
            basis_c?: number;
            pct_per_c?: number;
            min_pct?: number;
            max_pct?: number;
        };
        RainFactorSettings: {
            forecast_days?: number;
            threshold_prob?: number;
            reduce_above_mm?: number;
            zero_above_mm?: number;
            forecast_decay?: number;
        };
        SequenceOverride: {
            basis_min_per_zone?: number | null;
            watchdog_min?: number | null;
            paused?: boolean;
        };
        AppSettings: {
            sequences?: {
                [key: string]: components["schemas"]["SequenceOverride"];
            };
            factors?: {
                temp?: components["schemas"]["TempFactorSettings"];
                rain?: components["schemas"]["RainFactorSettings"];
            };
            notify_targets?: string[];
            token_lifetime_days?: number;
            auto_login_enabled?: boolean;
        };
        UserPreferences: {
            /** @enum {string} */
            theme?: "dark" | "light";
            /** @enum {string} */
            language?: "de" | "en";
        };
        LoginRequest: {
            password: string;
            /** @description Optional label shown in token list */
            device_label?: string;
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        AuthToken: {
            /** @description First 8 chars, for identification only */
            token_prefix: string;
            device_label?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            expires_at: string;
        };
        Error: {
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok";
                        ha_connected?: boolean;
                        version?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    autoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    embed_param_present: boolean;
                    device_label?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Trigger conditions not met */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"][];
                };
            };
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    setMaster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    on: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        master_on?: boolean;
                    };
                };
            };
        };
    };
    listSequences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SequenceState"][];
                };
            };
        };
    };
    getSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SequenceState"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    startSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartSequenceRequest"];
            };
        };
        responses: {
            /** @description Start accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mutex conflict — another sequence is already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sequence is disabled or master switch is off */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    pauseSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pause accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sequence is not currently running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    stopSequence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sequence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stop accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sequence is not currently running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listValves: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValveState"][];
                };
            };
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"][];
                };
            };
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deletePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                sequence_id?: string;
                zone_id?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistory"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferences"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
        };
    };
}
